-- Supabase SQL to create records table
-- Run this in Supabase Dashboard > SQL Editor

-- Create records table
CREATE TABLE IF NOT EXISTS records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    village TEXT NOT NULL,
    price NUMERIC DEFAULT 0,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE records ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read" ON records
    FOR SELECT USING (true);

-- Allow authenticated insert
CREATE POLICY "Allow authenticated insert" ON records
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Allow authenticated update
CREATE POLICY "Allow authenticated update" ON records
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Allow authenticated delete
CREATE POLICY "Allow authenticated delete" ON records
    FOR DELETE USING (auth.role() = 'authenticated');

-- Create index for search
CREATE INDEX IF NOT EXISTS idx_records_name ON records(name);
CREATE INDEX IF NOT EXISTS idx_records_village ON records(village);

-- Insert sample data (optional)
INSERT INTO records (name, village, price, note) VALUES
('Shri Sanjay Kumar Tiwari', 'Tiwari Barhawa', 51, NULL),
('Jitendra Sharma', 'Mahuawa', 201, NULL),
('Rohit Sharma', 'Mahuawa', 201, NULL),
('Divesh Sharma', 'Mahuawa', 401, NULL),
('Harinayaran Singh', 'Mohanapar', 51, NULL),
('Govinda Pandit', 'Mahuamari', 501, NULL),
('Dinanath Sharma', 'Ruka (Pattitola)', 501, NULL),
('Shivbali Singh', 'Barhajia', 51, NULL),
('Ramnath Ram', 'Bhopatpur', 51, NULL),
('Manoj Singh (Mukhiya)', 'Mohanapar', 101, NULL)
ON CONFLICT DO NOTHING;

-- Verify
SELECT * FROM records LIMIT 5;