// Supabase Configuration
window.SUPABASE_URL = 'https://agtoknvwtfipcumxvcrj.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFndG9rbnZ3dGZpcGN1bXh2Y3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcyMTA3ODUsImV4cCI6MjA5Mjc4Njc4NX0.EYG0gsppdHQtpk8J_3zHzw4aCrt3EetE-C7YUn3j5wA';
window.SUPABASE_SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFndG9rbnZ3dGZpcGN1bXh2Y3JqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzIxMDc4NSwiZXhwIjoyMDkyNzg2Nzg1fQ.Wx2HnwO6YkdIbSfTShOmudtFLdJR0nguRITEaafFmS8';

console.log('Supabase config loaded:', window.SUPABASE_URL);